server:
  port: 8080

spring:
  application:
    name: customers
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Corrected dialect name
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true