server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'password'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Corrected dialect name
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true